config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :bugs
  
  root 'bugs#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_many :bugs
    validates :lname, :fname, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 105},
        uniqueness: { case_sensitive: false },
        format: { with: VALID_EMAIL_REGEX }
    validates :thumbnail, allow_blank: true,
        format: {with:%r{\.(gif|jpg|png)\Z}i,
        message: 'must be a URL for GIF, JPG or PNG image.'}
end

app/models/bug.rb
class Bug < ActiveRecord::Base
    belongs_to :author
    
    validates :title, presence: true, length: {minimum: 5, maximum: 80}
    validates :description, presence: true, length: {minimum: 20, maximum: 600}
    
    enum issue_type: [:issue, :enhancement, :feature]
    enum priority: [:low, :medium, :high]
    enum status: [:open, :closed, :monitor]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:lname, :fname, :email, :thumbnail)
    end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_issue_types
  before_action :set_priorities
  before_action :set_statuses
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  before_action :all_bugs, only:[:index, :create, :destroy, :update]
  
  
  respond_to :html, :js
  
  def all_bugs
    @bugs = Bug.all
  end

  # GET /bugs
  # GET /bugs.json
  def index
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  
  def create
    @bug = Bug.new(bug_params)
    author = Author.find(bug_params[:author_id])
    @bug.build_author(:id => author.id)
    @bug.save!
    @current_bug = @bug
  end
  
  # def create
  #   @bug = Bug.new(bug_params)

  #   respond_to do |format|
  #     if @bug.save
  #       format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
  #       format.json { render :show, status: :created, location: @bug }
  #       author = Author.find(bug_params[:author_id])
  #       @bug.build_author(:id => author.id)
  #     else
  #       format.html { render :new }
  #       format.json { render json: @bug.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  
  def update
   @bug.update!(bug_params)
  end

  # def update
  #   respond_to do |format|
  #     if @bug.update(bug_params)
  #       format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @bug }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @bug.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  
  def destroy
   @bug.destroy!
  end

  # def destroy
  #   @bug.destroy
  #   respond_to do |format|
  #     format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end
    
    
    def set_issue_types
      @issue_types = Bug.issue_types
    end
    
    def set_priorities
      @priorities = Bug.priorities
    end
    
    def set_statuses
      @statuses = Bug.statuses
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description, :issue_type, :priority, :status, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Lname</th>
      <th>Fname</th>
      <th>Email</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.lname %></td>
        <td><%= author.fname %></td>
        <td><%= author.email %></td>
        <td><%= author.thumbnail %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lname:</strong>
  <%= @author.lname %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @author.fname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= @author.thumbnail %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/bugs/_bug.html.erb
<% if bug == @current_bug %>
    <div id="current_bug" class="description">
<% else %>
    <div class="description">
<% end %>

        <div class="description_title"> <%= bug.title %> </div>
        <div class="description_info">
            <span class="date"> <%= bug.updated_at.to_formatted_s(:long_ordinal) %>
            </span>
            <span class="author"> By <%= (bug.author.try(:lname) || "NA") %>
            </span>
        </div>
        <div class="description_text"> <%= bug.description %> </div>
        <div class="actions">
            <%= link_to 'Show', bug %>
            <%= link_to 'Edit', edit_bug_path(bug), remote: true %>
            <%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
        </div>
    </div>

app/views/bugs/_form.html.erb
<%= form_for(@bug, remote: true) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.select :author_id,
      options_for_select(Author.all.collect {|a| ["#{a.lname},
      #{a.fname}", a.id]},
      selected: (@bug.author ? @bug.author.id : Author.first.id)),
      {} %>
  </div>
  
  <div class="field">
    <%= f.label :issue_type %><br>
    <%= f.select :issue_type, options_for_select(@issue_types.collect {|s| [s[0].humanize, s[0], s[0]]}, selected: @bug.issue_type), {} %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.select :priority, options_for_select(@priorities.collect {|s| [s[0].humanize, s[0], s[0]]}, selected: @bug.priority), {} %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(@statuses.collect {|s| [s[0].humanize, s[0], s[0]]}, selected: @bug.status), {} %>
  </div>
  <div class="actions" id="submitbutton">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/create.js.erb
$('#bugs').html("<%= j (render @bugs) %>");
$('#blog-form').slideUp(350);
$('#current_bug').css({'background-color' : '#88ff88'}).animate({'background-color': '#ffffff'}, 1000);

app/views/bugs/destroy.js.erb
$('#bugs').html("<%= j (render @bugs) %>");

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/edit.js.erb
$('#blog-form').html("<%= j (render 'form') %>");
$('#blog-form').slideDown(350);

app/views/bugs/index.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<h1>Recent Postings</h1>

<span class="btn">
  <%= link_to 'New Bug', new_bug_path, remote: true %>
</span>

<div id="bugs">
  <%= render @bugs %>
</div>

<div id="blog-form" style="display:none;"></div>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form' %>

<%= link_to 'Back', bugs_path %>

app/views/bugs/new.js.erb
$('#blog-form').html("<%= j (render 'form') %>");
$('#blog-form').slideDown(0);
if((obj = document.getElementById("submitbutton")) && obj != null){
    window.scrollTo(0, obj.offsetTop);
}

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bug.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bug.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= (@bug.author.try(:lname) || "NA")%>
</p>

<p>
  <strong>Issue type:</strong>
  <%= @bug.issue_type %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @bug.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bug.status %>
</p>

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/update.js.erb
$('#bugs').html("<%= j (render @bugs) %>");
$('#blog-form').slideUp(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinkstrack' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= controller.controller_name %>">
    <div id="banner">
      <%= @page_title || "My Blog!" %>
    </div>
    <div id="columns">
      <div id="side">
        <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/authors">Authors</a></li>
        <li><a href="/contact">Contact</a></li>
        </ul>
      </div>
      <div id="main">
      <%= yield %>
      </div>
    </div>
  </body>
</html>